security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        target: app_home

  role_hierarchy:
    ROLE_ADMIN: [ ROLE_AUTHOR, ROLE_USER ]
    ROLE_AUTHOR: [ ROLE_USER ]

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/author, roles: ROLE_AUTHOR }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/post/new, roles: ROLE_AUTHOR }
    - { path: ^/post, roles: ROLE_AUTHOR }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
